/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author abc
 */
public class productadd extends javax.swing.JFrame {

    /**
     * Creates new form productadd
     */
    public productadd() {
        initComponents();
        doe.setDateFormatString("yyyy-MM-dd");
        doe1.setDateFormatString("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        qua = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        doe = new com.toedter.calendar.JDateChooser();
        doe1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 180, 280, 300));
        setMinimumSize(new java.awt.Dimension(530, 430));
        setSize(new java.awt.Dimension(530, 410));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel1.setText("Name of the Product :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 25, 199, 34);

        jLabel2.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel2.setText("Price of the Product :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 86, 199, 34);

        jLabel3.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel3.setText("Quantity Avaliable :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(26, 147, 199, 34);

        jLabel4.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel4.setText("Expiry Date of Product :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 208, 199, 34);
        getContentPane().add(price);
        price.setBounds(326, 88, 172, 34);
        getContentPane().add(name);
        name.setBounds(326, 27, 172, 34);
        getContentPane().add(qua);
        qua.setBounds(326, 149, 172, 34);

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(submitbutton);
        submitbutton.setBounds(26, 323, 472, 23);

        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(26, 357, 472, 23);
        getContentPane().add(doe);
        doe.setBounds(326, 208, 172, 34);
        getContentPane().add(doe1);
        doe1.setBounds(326, 260, 172, 36);

        jLabel5.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        jLabel5.setText("Manufacture Date :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(26, 260, 147, 36);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Secure/2.jpg"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(530, 410));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 530, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new adminlogin().setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        String NameMy= null;
        int p=0;
        int q=0;
        Connection conn= null;
        ResultSet rs= null;
        PreparedStatement stmt= null;
    try {
        conn=Login.guicon();
        String qu="INSERT into product (p_name,quantity,price,man_date,exp_date) values (?,?,?,?,?)";
        stmt= conn.prepareStatement(qu);
        NameMy=name.getText();
        p = Integer.parseInt(price.getText());
        q = Integer.parseInt(qua.getText());
        stmt.setString(1,NameMy);
        stmt.setInt(2,q);
        stmt.setInt(3,p);
        stmt.setString(4,((JTextField)doe1.getDateEditor().getUiComponent()).getText());
        stmt.setString(5,((JTextField)doe.getDateEditor().getUiComponent()).getText());
        int i=stmt.executeUpdate();
        System.out.println("Rows affected"+i);
        JOptionPane.showMessageDialog(null, "Product Added Successfully");
         this.setVisible(false);
        new adminlogin().setVisible(true);
        
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_submitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private com.toedter.calendar.JDateChooser doe;
    private com.toedter.calendar.JDateChooser doe1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qua;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
