/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abc
 */
public class specs extends javax.swing.JFrame {

    /**
     * Creates new form specs
     */
    public specs() {
        initComponents();
         exp.setDateFormatString("yyyy-MM-dd");
         man.setDateFormatString("yyyy-MM-dd");
        fetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pri = new javax.swing.JTextField();
        qu = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pr = new javax.swing.JLabel();
        exp = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        man = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 160));
        setMinimumSize(new java.awt.Dimension(818, 419));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Price", "Quantity", "Expiration Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 438, 258);

        jLabel1.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel1.setText("Product ID :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(474, 60, 114, 27);

        jLabel3.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel3.setText("Product name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(474, 105, 114, 27);

        jLabel4.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel4.setText("Expiration Date :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(474, 284, 133, 27);

        jLabel5.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel5.setText("Quantity :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(474, 197, 114, 27);

        pri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priActionPerformed(evt);
            }
        });
        getContentPane().add(pri);
        pri.setBounds(613, 107, 142, 23);

        qu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(qu);
        qu.setBounds(613, 199, 142, 23);

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(626, 339, 96, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(492, 339, 98, 23);

        pr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(pr);
        pr.setBounds(613, 60, 142, 27);
        getContentPane().add(exp);
        exp.setBounds(613, 291, 142, 20);

        jLabel2.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel2.setText("Price :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(474, 150, 95, 29);

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price);
        price.setBounds(613, 156, 142, 20);

        jLabel6.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel6.setText("Manufacture Date :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(474, 242, 133, 24);
        getContentPane().add(man);
        man.setBounds(613, 246, 142, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Secure/2_1.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            // TODO add your handling code here:
            int selectedRow=jTable1.getSelectedRow();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            pr.setText(model.getValueAt(selectedRow, 0).toString());
            pri.setText(model.getValueAt(selectedRow, 1).toString());
            qu.setText(model.getValueAt(selectedRow, 2).toString());
            price.setText(model.getValueAt(selectedRow, 3).toString());
            String str=(model.getValueAt(selectedRow, 5).toString());
            Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(str);
            exp.setDate(date1);
            String str1=(model.getValueAt(selectedRow, 4).toString());
            Date date2=new SimpleDateFormat("yyyy-MM-dd").parse(str1);
            man.setDate(date2);
//jDateChooser2.setString(4,((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
                    } catch (ParseException ex) {
            Logger.getLogger(specs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
        
        try {
            Connection conn;
            conn = Login.guicon();
            String q="update product set p_name=?,price=?,quantity=?,man_date=?,exp_date=? where p_name=?";
            PreparedStatement stmt=conn.prepareStatement(q);
            stmt.setString(1,pri.getText());
            stmt.setString(2,price.getText());
            stmt.setString(3,qu.getText());
            stmt.setString(5,((JTextField)exp.getDateEditor().getUiComponent()).getText());
            stmt.setString(4,((JTextField)man.getDateEditor().getUiComponent()).getText());
            stmt.setString(6,pri.getText());
            stmt.executeUpdate();
            System.out.println("Hello");
            System.out.println(pri.getText());
            fetch();
        }catch (SQLException ex) {
            Logger.getLogger(specs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new adminlogin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void priActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

     public void fetch()
        {
         try{
         ResultSet rs=null;
         Connection conn=null;
         conn=Login.guicon();
         String q="select * from product";
         PreparedStatement stmt=null;
         stmt=conn.prepareStatement(q);
         rs=stmt.executeQuery();
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
         catch (SQLException ex) {
         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(specs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(specs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(specs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(specs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new specs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser exp;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser man;
    private javax.swing.JLabel pr;
    private javax.swing.JTextField pri;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qu;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
